### ISSUE TITLE
max/min depth mode for ruby1.9.x mode

### ISSUE THREAD

**Issue by flagos** [djberg96/file-find#2]
Hi,

When activating maxdepth mode in ruby1.9.x, I found a bug. find.rb#270, @path were considered as an array rather than a string.

I've seen you've got a workaround to this, I think it just has been forgotten in this case. I've forked your repo and make a patch on it.

Please have a look: https://github.com/flagos/file-find

Thanks !

**Comment by djberg96** [comment]
Long overdue update for this ticket. The real issue is that mindepth and maxdepth don't work properly if there are multiple :paths set.

**Comment by djberg96** [comment]
I think the real solution is to use a recursive approach, which will mean overhauling the code internally.
